# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39d2813e7cc76741ca17577b60f473c432a17de6ff4512ccd20b239d2909a7876fb02ffc75212732b53bf5c8d14e9ee73246d71692ac1d0902dfee1573d258a7

test:
  secret_key_base: 6a274169762569c32926629c69952b76b2cb79da6afb9b0c81f686b07d45b8931fe96b14fcee8187bb6fe492f19166a1437101879662801b56d350b353ea2876

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
